name: Data request
description: >
  Request a type of data available for download from the
  <a href="https://pacfin.psmfc.org/" target="_blank">PacFIN data warehouse</a>.
title: "Data request for species [replace with your species]"
labels: ["type: request"]
assignees:
  - kellijohnson-NOAA
  - chantelwetzel-NOAA
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out the PacFIN request form.
  - type: textarea
    id: species
    attributes:
      label: Identify the common name(s) or PacFIN species code(s)
      description: >
        Please be as specific as possible regarding the species that you are
        interested in. For example, do you know the nominal species codes? If
        yes, please add them.
  - type: dropdown
    id: data
    attributes:
      label: Type of data needed
      multiple: true
      options:
        - catch
        - biological data
        - log book (not yet available)
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: >
        Please provide any additional information that could be relevant to your
        data pull.
  - type: checkboxes
    id: clearance
    attributes:
      label: Do you you have clearance to access these data?
      description: >
        By checking the following box you agree that you have access to
        confidential data from PacFIN, which means you have a signed data
        sharing agreement that is on file with PacFIN. And, you also agree that
        you will not share these data with those that do not have the same
        clearance.
      options:
        - label: I agree that I have clearance (as described above)
          required: true
